In [ ]:
import tensorflow as tf

In [ ]:
#Tensor initialization
x = tf.constant(4,shape=(1,1))
x = tf.constant([[1,2,3,4],[5,6,7,8]],shape=(2,4))
x = tf.ones((4,2))
x = tf.zeros((2,3))
x = tf.eye(4) #identical matrix)
x = tf.random.normal((3,4), mean=0, stddev=1) # std normal distribution
x = tf.random.uniform((2,3), minval=3, maxval=7)
x = tf.range(start=2, limit=10, delta=3)
x = tf.cast(x, dtype=tf.float16)
print(x)


tf.Tensor([2. 5. 8.], shape=(3,), dtype=float16)


In [ ]:
#Mathematical Ops on Tensors
x = tf.constant([1,2,3])
y = tf.constant([99,98,97])
z = tf.add(x, y)
z = x+y

z = tf.subtract(y,x)
z = x-y

z = tf.divide(y, x) #element wise division
z = y / x

z = tf.multiply(x, y) #element wise multiplication
z = x*y

z = tf.tensordot(x, y, axes =1)
z = tf.reduce_sum(x*y, axis=0)

z = x ** 3 #exponentiation of each element

x = tf.random.normal((3,4))
y = tf.random.uniform((4,5))
z = tf.matmul(x, y)
z = x @ y
print(z)


tf.Tensor(
[[-1.5914319  -1.4030652  -1.2472174  -0.51465994 -0.2659195 ]
 [-2.1524441  -1.584168   -1.8700377  -0.74975777 -1.6695043 ]
 [ 1.3897814   0.47323477  1.0778824   1.1593405   0.30847695]], shape=(3, 5), dtype=float32)


In [ ]:
#Indexing
x = tf.constant([1,2,3,4,5,6,7])
#print(x[1:5])
#print(x[1::3])
#print(x[3::-1])   #reveresed order

indices = tf.constant([2,4])
x_ind = tf.gather(x, indices)
print(x_ind)

x = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(x[0,1:2])
print(x[0:2,1:2])

tf.Tensor([3 5], shape=(2,), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor(
[[2]
 [5]], shape=(2, 1), dtype=int32)


In [ ]:
#Reshaping
x = tf.range(10)
x = tf.reshape(x, (2,5))
x = tf.transpose(x)
print(x)

tf.Tensor(
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]], shape=(5, 2), dtype=int32)


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
from tensorflow.keras import regularizers


In [ ]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()
print(x_train.shape)
x_train = x_train.reshape(-1,784).astype("float32")/255.0
x_test = x_test.reshape(-1,784).astype("float32")/255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
(60000, 28, 28)


In [ ]:
model = keras.Sequential(
    [
        keras.Input(shape=(28*28,)),
        layers.Dense(512,activation="relu", name='first_layer'),
        layers.Dense(256,activation="relu", name='second_layer'),
        layers.Dense(10),
    ]
)
print(model.summary())
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

model.fit(x_train,y_train,batch_size=32, epochs=5,verbose=2)
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ first_layer (Dense)             │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ second_layer (Dense)            │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 535,818 (2.04 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

None
Epoch 1/5
1875/1875 - 11s - 6ms/step - accuracy: 0.9442 - loss: 0.1857
Epoch 2/5
1875/1875 - 10s - 6ms/step - accuracy: 0.9756 - loss: 0.0774
Epoch 3/5
1875/1875 - 21s - 11ms/step - accuracy: 0.9825 - loss: 0.0536
Epoch 4/5
1875/1875 - 11s - 6ms/step - accuracy: 0.9869 - loss: 0.0398
Epoch 5/5
1875/1875 - 10s - 5ms/step - accuracy: 0.9898 - loss: 0.0323
313/313 - 1s - 3ms/step - accuracy: 0.9812 - loss: 0.0774


[0.07735703885555267, 0.9811999797821045]

In [ ]:
input = keras.Input(shape=(28*28,))
x = layers.Dense(512,activation='relu', kernel_regularizer=regularizers.l2(0.01))(input)
x = layers.Dense(256,activation='relu')(x)
outputs = layers.Dense(10, activation='softmax')(x)
model=keras.Model(inputs=input, outputs=outputs)
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(),
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)
model.fit(x_train,y_train,batch_size=32, epochs=5,verbose=2)
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

Epoch 1/5
1875/1875 - 16s - 9ms/step - accuracy: 0.9151 - loss: 0.6036
Epoch 2/5
1875/1875 - 14s - 7ms/step - accuracy: 0.9449 - loss: 0.3249
Epoch 3/5
1875/1875 - 13s - 7ms/step - accuracy: 0.9518 - loss: 0.2773
Epoch 4/5
1875/1875 - 12s - 6ms/step - accuracy: 0.9564 - loss: 0.2513
Epoch 5/5
1875/1875 - 12s - 6ms/step - accuracy: 0.9574 - loss: 0.2412
313/313 - 1s - 3ms/step - accuracy: 0.9574 - loss: 0.2356


[0.23559635877609253, 0.9574000239372253]

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
!pip install ultralytics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 20.6 MB/s eta 0:00:00


In [ ]:
# Predict using a pretrained YOLO model (e.g., YOLO11n) on an image just for inference
!yolo predict model=yolo11n.pt source='https://ultralytics.com/images/bus.jpg'

Creating new Ultralytics Settings v0.0.6 file ✅ 
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Ultralytics 8.4.2 🚀 Python-3.12.12 torch-2.9.0+cpu CPU (AMD EPYC 7B12)
YOLO11n summary (fused): 100 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

image 1/1 /content/bus.jpg: 640x480 4 persons, 1 bus, 269.0ms
Speed: 18.1ms preprocess, 269.0ms inference, 42.2ms postprocess per image at shape (1, 3, 640, 480)
Results saved to /content/runs/detect/predict
💡 Learn more at https://docs.ultralytics.com/modes/predict


In [ ]:
!yolo task=detect mode=predict model=yolov8n.pt source='WIN_20251023_18_40_33_Pro.jpg'

Ultralytics 8.4.2 🚀 Python-3.12.12 torch-2.9.0+cpu CPU (AMD EPYC 7B12)
YOLOv8n summary (fused): 72 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ultralytics/cfg/__init__.py", line 985, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ultralytics/engine/model.py", line 536, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ultralytics/engine/predictor.py", line 244, in predict_cli
    for _ in gen:  # sourcery skip: remove-empty-nested-block, noqa
             ^^^
  File "/usr/local/lib/python3.12/dist-package

In [ ]:
!yolo task=segment mode=predict model=yolov8n-seg.pt source='WIN_20251023_18_40_33_Pro.jpg'

Ultralytics 8.4.2 🚀 Python-3.12.12 torch-2.9.0+cpu CPU (AMD EPYC 7B12)
YOLOv8n-seg summary (fused): 85 layers, 3,404,320 parameters, 0 gradients, 12.0 GFLOPs

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ultralytics/cfg/__init__.py", line 985, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ultralytics/engine/model.py", line 536, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ultralytics/engine/predictor.py", line 244, in predict_cli
    for _ in gen:  # sourcery skip: remove-empty-nested-block, noqa
             ^^^
  File "/usr/local/lib/python3.12/dist-pa

In [ ]:
from ultralytics import YOLO
model=YOLO("yolov8n-cls.pt")
model.classify(source="myself.jpg")

AttributeError: 'ClassificationModel' object has no attribute 'classify'